import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "./components/footer";
import Header from "./components/header";
import { AuthProvider } from "./components/providers/AuthProvider";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Next Eccomerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="flex h-full flex-col">
          <AuthProvider>
            <Header />

            <div className="flex-1 pt-20 md:pt-28">{children}</div>

            <Footer />
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
